/**
 * BehaviorOS AutoDocumentationTrigger — Automatically generates documentation
 * when subtasks complete. Documentation type depends on subtask type.
 *
 * Mapping:
 *   design        → docs/architecture/{title}.md
 *   implementation → docs/features/{title}.md + changelog
 *   testing       → docs/testing/{title}.md
 *   review        → docs/reviews/{title}.md
 *   security      → docs/security/advisory-{date}.md
 *   deployment    → docs/deployments/{title}.md
 *   documentation → (tracked, no file generated)
 *   compliance    → docs/compliance/{title}.md
 *
 * Part of the AutonomousOrchestrator engine (Phase 2).
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { SubTask } from '@behavioros/schemas';

// ============================================================
// Types
// ============================================================

/**
 * DocGenerationResult — Configuration and options interface.
 */
export interface DocGenerationResult {
  docsGenerated: string[];
}

/**
 * AutoDocumentationOptions — Configuration and options interface.
 */
export interface AutoDocumentationOptions {
  /** Root path of the project (defaults to process.cwd()) */
  projectRoot?: string;
  /** Whether to actually write files (defaults to true) */
  writeFiles?: boolean;
}

// ============================================================
// AutoDocumentationTrigger
// ============================================================

/**
 * AutoDocumentationTrigger — ============================================================.
 */
export class AutoDocumentationTrigger {
  private projectRoot: string;
  private writeFilesEnabled: boolean;
  private generatedDocs: string[] = [];

  constructor(options: AutoDocumentationOptions = {}) {
    this.projectRoot = options.projectRoot ?? process.cwd();
    this.writeFilesEnabled = options.writeFiles ?? true;
  }

  /**
   * Called when a subtask completes successfully.
   * Generates documentation based on the subtask type.
   */
  async onSubtaskComplete(
    subtask: SubTask,
    output: unknown,
    projectPath?: string,
  ): Promise<DocGenerationResult> {
    const activePath = projectPath ?? this.projectRoot;
    const docsGenerated: string[] = [];

    switch (subtask.type) {
      case 'design':
        docsGenerated.push(await this.generateDesignDoc(subtask, output, activePath));
        break;
      case 'implementation':
        docsGenerated.push(await this.generateFeatureDoc(subtask, output, activePath));
        docsGenerated.push(this.generateChangelogEntry(subtask));
        break;
      case 'testing':
        docsGenerated.push(await this.generateTestingDoc(subtask, output, activePath));
        break;
      case 'review':
        docsGenerated.push(await this.generateReviewDoc(subtask, output, activePath));
        break;
      case 'security':
        docsGenerated.push(await this.generateSecurityAdvisory(subtask, output, activePath));
        break;
      case 'deployment':
        docsGenerated.push(await this.generateDeploymentDoc(subtask, output, activePath));
        break;
      case 'documentation':
        // Just track that documentation was completed
        docsGenerated.push(`tracked:documentation-${subtask.id}`);
        break;
      case 'compliance':
        docsGenerated.push(await this.generateComplianceDoc(subtask, output, activePath));
        break;
      default:
        // Unknown subtask type — generate generic doc
        docsGenerated.push(await this.generateGenericDoc(subtask, output, activePath));
    }

    this.generatedDocs.push(...docsGenerated);

    return { docsGenerated };
  }

  /**
   * Get the list of all generated documentation paths.
   */
  getGeneratedDocs(): string[] {
    return [...this.generatedDocs];
  }

  /**
   * Clear the generated docs list (for testing).
   */
  clear(): void {
    this.generatedDocs = [];
  }

  // ─── Design Documentation ──────────────────────────────────

  private async generateDesignDoc(
    subtask: SubTask,
    _output: unknown,
    projectPath: string,
  ): Promise<string> {
    const dir = join(projectPath, 'docs', 'architecture');
    const filename = `${this.sanitizeFilename(subtask.title)}.md`;
    const filePath = join(dir, filename);

    const content = `# Architecture: ${subtask.title}

## Overview
${subtask.description ?? 'Design document for architectural decision.'}

## Status
- **Generated:** ${new Date().toISOString()}
- **Subtask ID:** ${subtask.id}
- **Type:** Architecture Design

## Details
This document was auto-generated by the BehaviorOS AutonomousOrchestrator
when the design subtask was completed.
`;

    await this.ensureAndWrite(dir, filePath, content);
    return filePath;
  }

  // ─── Feature Documentation ─────────────────────────────────

  private async generateFeatureDoc(
    subtask: SubTask,
    _output: unknown,
    projectPath: string,
  ): Promise<string> {
    const dir = join(projectPath, 'docs', 'features');
    const filename = `${this.sanitizeFilename(subtask.title)}.md`;
    const filePath = join(dir, filename);

    const content = `# Feature: ${subtask.title}

## Description
${subtask.description ?? 'Feature implementation documentation.'}

## Metadata
- **Generated:** ${new Date().toISOString()}
- **Subtask ID:** ${subtask.id}
- **Type:** Feature Implementation

## Changelog
- Implemented: ${new Date().toISOString()}
`;

    await this.ensureAndWrite(dir, filePath, content);
    return filePath;
  }

  // ─── Testing Documentation ─────────────────────────────────

  private async generateTestingDoc(
    subtask: SubTask,
    _output: unknown,
    projectPath: string,
  ): Promise<string> {
    const dir = join(projectPath, 'docs', 'testing');
    const filename = `${this.sanitizeFilename(subtask.title)}.md`;
    const filePath = join(dir, filename);

    const content = `# Test: ${subtask.title}

## Scope
${subtask.description ?? 'Testing documentation.'}

## Execution
- **Generated:** ${new Date().toISOString()}
- **Subtask ID:** ${subtask.id}

## Results
Testing completed as part of the autonomous execution pipeline.
`;

    await this.ensureAndWrite(dir, filePath, content);
    return filePath;
  }

  // ─── Review Documentation ──────────────────────────────────

  private async generateReviewDoc(
    subtask: SubTask,
    _output: unknown,
    projectPath: string,
  ): Promise<string> {
    const dir = join(projectPath, 'docs', 'reviews');
    const filename = `${this.sanitizeFilename(subtask.title)}.md`;
    const filePath = join(dir, filename);

    const content = `# Review: ${subtask.title}

## Context
${subtask.description ?? 'Code review documentation.'}

## Metadata
- **Generated:** ${new Date().toISOString()}
- **Subtask ID:** ${subtask.id}
- **Reviewer:** AutonomousOrchestrator

## Findings
Review completed autonomously.
`;

    await this.ensureAndWrite(dir, filePath, content);
    return filePath;
  }

  // ─── Security Advisory ─────────────────────────────────────

  private async generateSecurityAdvisory(
    subtask: SubTask,
    _output: unknown,
    projectPath: string,
  ): Promise<string> {
    const date = new Date().toISOString().split('T')[0]!;
    const dir = join(projectPath, 'docs', 'security');
    const filename = `advisory-${date}.md`;
    const filePath = join(dir, filename);

    const content = `# Security Advisory: ${date}

## Title
${subtask.title}

## Description
${subtask.description ?? 'Security advisory.'}

## Status
- **Generated:** ${new Date().toISOString()}
- **Subtask ID:** ${subtask.id}
- **Severity:** Determined by security scan

## Actions Taken
Security review completed autonomously.
`;

    await this.ensureAndWrite(dir, filePath, content);
    return filePath;
  }

  // ─── Deployment Documentation ──────────────────────────────

  private async generateDeploymentDoc(
    subtask: SubTask,
    _output: unknown,
    projectPath: string,
  ): Promise<string> {
    const dir = join(projectPath, 'docs', 'deployments');
    const filename = `${this.sanitizeFilename(subtask.title)}.md`;
    const filePath = join(dir, filename);

    const content = `# Deployment: ${subtask.title}

## Overview
${subtask.description ?? 'Deployment documentation.'}

## Timestamp
- **Generated:** ${new Date().toISOString()}
- **Subtask ID:** ${subtask.id}

## Deployment Details
Deployment executed autonomously.
`;

    await this.ensureAndWrite(dir, filePath, content);
    return filePath;
  }

  // ─── Compliance Documentation ──────────────────────────────

  private async generateComplianceDoc(
    subtask: SubTask,
    _output: unknown,
    projectPath: string,
  ): Promise<string> {
    const dir = join(projectPath, 'docs', 'compliance');
    const filename = `${this.sanitizeFilename(subtask.title)}.md`;
    const filePath = join(dir, filename);

    const content = `# Compliance: ${subtask.title}

## Scope
${subtask.description ?? 'Compliance documentation.'}

## Verification
- **Generated:** ${new Date().toISOString()}
- **Subtask ID:** ${subtask.id}

## Status
Compliance checks completed autonomously.
`;

    await this.ensureAndWrite(dir, filePath, content);
    return filePath;
  }

  // ─── Generic Documentation (fallback) ──────────────────────

  private async generateGenericDoc(
    subtask: SubTask,
    _output: unknown,
    projectPath: string,
  ): Promise<string> {
    const dir = join(projectPath, 'docs', 'generated');
    const filename = `${this.sanitizeFilename(subtask.title)}.md`;
    const filePath = join(dir, filename);

    const content = `# ${subtask.title}

## Description
${subtask.description ?? 'Auto-generated documentation.'}

## Metadata
- **Generated:** ${new Date().toISOString()}
- **Subtask ID:** ${subtask.id}
- **Type:** ${subtask.type}
- **Required Skill:** ${subtask.requiredSkill}
`;

    await this.ensureAndWrite(dir, filePath, content);
    return filePath;
  }

  // ─── Changelog Entry ───────────────────────────────────────

  private generateChangelogEntry(subtask: SubTask): string {
    return `changelog:${subtask.id}:${subtask.title}`;
  }

  // ─── Helpers ───────────────────────────────────────────────

  private async ensureAndWrite(dir: string, filePath: string, content: string): Promise<void> {
    if (!this.writeFilesEnabled) return;

    try {
      await mkdir(dir, { recursive: true });
      await writeFile(filePath, content, 'utf-8');
    } catch (error) {
      console.warn(
        `AutoDocumentationTrigger: Failed to write ${filePath}:`,
        error instanceof Error ? error.message : String(error),
      );
    }
  }

  private sanitizeFilename(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .substring(0, 100);
  }
}
