import type { Agent, AuditEvent, DnaPackage, GovernanceRule, Mission, QualityGate } from '@/types';

export const missions: Mission[] = [
  {
    id: 'MSN-001',
    title: 'Implement Authentication System',
    description: 'Set up Better Auth with email OTP and session management',
    type: 'build',
    priority: 'critical',
    status: 'completed',
    assignedTo: ['Architect', 'Engineer'],
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-03T15:30:00Z',
    progress: 100,
    tags: ['auth', 'security', 'backend'],
  },
  {
    id: 'MSN-002',
    title: 'Design System Token Architecture',
    description: 'Create design tokens for the entire UI system',
    type: 'build',
    priority: 'high',
    status: 'completed',
    assignedTo: ['Product', 'Engineer'],
    createdAt: '2026-07-02T09:00:00Z',
    updatedAt: '2026-07-04T12:00:00Z',
    progress: 100,
    tags: ['design', 'ui', 'tokens'],
  },
  {
    id: 'MSN-003',
    title: 'Database Migration Strategy',
    description: 'Plan and execute Prisma migrations for v2 schema',
    type: 'build',
    priority: 'high',
    status: 'executing',
    assignedTo: ['Architect', 'Engineer'],
    createdAt: '2026-07-05T08:00:00Z',
    updatedAt: '2026-07-06T14:20:00Z',
    progress: 65,
    tags: ['database', 'migration', 'prisma'],
  },
  {
    id: 'MSN-004',
    title: 'Security Audit Pipeline',
    description: 'Run comprehensive security scan on all endpoints',
    type: 'review',
    priority: 'critical',
    status: 'executing',
    assignedTo: ['Security', 'QA'],
    createdAt: '2026-07-06T11:00:00Z',
    updatedAt: '2026-07-07T09:45:00Z',
    progress: 40,
    tags: ['security', 'audit', 'owasp'],
  },
  {
    id: 'MSN-005',
    title: 'Performance Optimization Sprint',
    description: 'Optimize bundle size and Core Web Vitals',
    type: 'build',
    priority: 'medium',
    status: 'draft',
    assignedTo: ['Engineer'],
    createdAt: '2026-07-07T10:00:00Z',
    updatedAt: '2026-07-07T10:00:00Z',
    progress: 0,
    tags: ['performance', 'frontend', 'optimization'],
  },
  {
    id: 'MSN-006',
    title: 'CI/CD Pipeline Enhancement',
    description: 'Add parallel test execution and caching layers',
    type: 'deploy',
    priority: 'medium',
    status: 'completed',
    assignedTo: ['DevOps'],
    createdAt: '2026-07-01T14:00:00Z',
    updatedAt: '2026-07-02T18:00:00Z',
    progress: 100,
    tags: ['ci', 'cd', 'devops'],
  },
  {
    id: 'MSN-007',
    title: 'API Contract Validation',
    description: 'Validate oRPC contracts match frontend expectations',
    type: 'review',
    priority: 'high',
    status: 'failed',
    assignedTo: ['QA', 'Engineer'],
    createdAt: '2026-07-04T09:00:00Z',
    updatedAt: '2026-07-05T16:00:00Z',
    progress: 30,
    tags: ['api', 'contracts', 'validation'],
  },
  {
    id: 'MSN-008',
    title: 'Mobile App Shell Setup',
    description: 'Initialize Expo project with navigation and auth flow',
    type: 'build',
    priority: 'medium',
    status: 'executing',
    assignedTo: ['Engineer', 'Product'],
    createdAt: '2026-07-06T08:30:00Z',
    updatedAt: '2026-07-07T11:00:00Z',
    progress: 25,
    tags: ['mobile', 'expo', 'react-native'],
  },
  {
    id: 'MSN-009',
    title: 'Monitoring Dashboard Setup',
    description: 'Configure Grafana dashboards for production metrics',
    type: 'monitor',
    priority: 'low',
    status: 'draft',
    assignedTo: ['DevOps'],
    createdAt: '2026-07-07T13:00:00Z',
    updatedAt: '2026-07-07T13:00:00Z',
    progress: 0,
    tags: ['monitoring', 'grafana', 'observability'],
  },
  {
    id: 'MSN-010',
    title: 'Documentation Overhaul',
    description: 'Rewrite API docs and add interactive examples',
    type: 'research',
    priority: 'low',
    status: 'executing',
    assignedTo: ['Product'],
    createdAt: '2026-07-05T10:00:00Z',
    updatedAt: '2026-07-07T08:00:00Z',
    progress: 55,
    tags: ['docs', 'api', 'documentation'],
  },
];

export const agents: Agent[] = [
  {
    id: 'AGT-001',
    name: 'Architect',
    role: 'System Architect',
    authority: 'High',
    status: 'working',
    reputation: 95,
    skills: ['System Design', 'DDD', 'API Architecture', 'Database Design'],
    missionsCompleted: 12,
    lastActive: '2026-07-07T14:30:00Z',
    avatar: '🏗️',
  },
  {
    id: 'AGT-002',
    name: 'Engineer',
    role: 'Senior Engineer',
    authority: 'High',
    status: 'working',
    reputation: 92,
    skills: ['TypeScript', 'React', 'Node.js', 'Prisma', 'Testing'],
    missionsCompleted: 18,
    lastActive: '2026-07-07T14:25:00Z',
    avatar: '⚙️',
  },
  {
    id: 'AGT-003',
    name: 'QA',
    role: 'Quality Assurance',
    authority: 'Medium',
    status: 'working',
    reputation: 88,
    skills: ['Testing', 'Playwright', 'Vitest', 'Contract Testing'],
    missionsCompleted: 9,
    lastActive: '2026-07-07T14:20:00Z',
    avatar: '🔍',
  },
  {
    id: 'AGT-004',
    name: 'Security',
    role: 'Security Specialist',
    authority: 'Critical',
    status: 'working',
    reputation: 97,
    skills: ['OWASP', 'Threat Modeling', 'Encryption', 'Auth Security'],
    missionsCompleted: 7,
    lastActive: '2026-07-07T14:15:00Z',
    avatar: '🛡️',
  },
  {
    id: 'AGT-005',
    name: 'DevOps',
    role: 'DevOps Engineer',
    authority: 'High',
    status: 'idle',
    reputation: 90,
    skills: ['Docker', 'CI/CD', 'Kubernetes', 'Terraform', 'Monitoring'],
    missionsCompleted: 11,
    lastActive: '2026-07-07T13:00:00Z',
    avatar: '🚀',
  },
  {
    id: 'AGT-006',
    name: 'Product',
    role: 'Product Manager',
    authority: 'High',
    status: 'idle',
    reputation: 85,
    skills: ['Product Strategy', 'UX Research', 'Documentation', 'Analytics'],
    missionsCompleted: 6,
    lastActive: '2026-07-07T12:00:00Z',
    avatar: '📋',
  },
];

export const governanceRules: GovernanceRule[] = [
  {
    id: 'GOV-001',
    name: 'No Secrets in Code',
    description: 'Prevent any hardcoded secrets, API keys, or credentials',
    level: 'critical',
    action: 'block',
    conditions: ['Contains API key pattern', 'Contains password literal', 'Contains secret string'],
    scope: 'All Code',
    enabled: true,
    createdAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'GOV-002',
    name: 'Type Safety Enforcement',
    description: 'All TypeScript code must pass strict type checking',
    level: 'critical',
    action: 'block',
    conditions: ['any type usage', 'implicit undefined', 'missing return type on exports'],
    scope: 'TypeScript',
    enabled: true,
    createdAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'GOV-003',
    name: 'Test Coverage Threshold',
    description: 'Minimum 80% test coverage for new code',
    level: 'high',
    action: 'escalate',
    conditions: ['Coverage below 80%', 'Critical path untested'],
    scope: 'Tests',
    enabled: true,
    createdAt: '2026-06-15T00:00:00Z',
  },
  {
    id: 'GOV-004',
    name: 'Performance Budget',
    description: 'Bundle size must stay within defined limits',
    level: 'high',
    action: 'warn',
    conditions: ['Bundle > 250KB', 'LCP > 2.5s', 'CLS > 0.1'],
    scope: 'Frontend',
    enabled: true,
    createdAt: '2026-06-20T00:00:00Z',
  },
  {
    id: 'GOV-005',
    name: 'Documentation Required',
    description: 'All public APIs must have JSDoc documentation',
    level: 'medium',
    action: 'warn',
    conditions: ['Missing JSDoc on export', 'No usage examples'],
    scope: 'Documentation',
    enabled: true,
    createdAt: '2026-06-25T00:00:00Z',
  },
  {
    id: 'GOV-006',
    name: 'Dependency Audit',
    description: 'Regular security audit of npm dependencies',
    level: 'medium',
    action: 'escalate',
    conditions: ['Critical vulnerability found', 'Outdated major version'],
    scope: 'Dependencies',
    enabled: true,
    createdAt: '2026-07-01T00:00:00Z',
  },
  {
    id: 'GOV-007',
    name: 'Commit Message Format',
    description: 'All commits must follow conventional commit format',
    level: 'low',
    action: 'log',
    conditions: ['Non-conventional format', 'Missing scope'],
    scope: 'Git',
    enabled: true,
    createdAt: '2026-07-01T00:00:00Z',
  },
  {
    id: 'GOV-008',
    name: 'Console Log Restriction',
    description: 'No console.log in production code',
    level: 'medium',
    action: 'block',
    conditions: ['console.log in src/', 'debug statement in production'],
    scope: 'Code Quality',
    enabled: false,
    createdAt: '2026-07-05T00:00:00Z',
  },
];

export const qualityGates: QualityGate[] = [
  {
    id: 'QG-001',
    name: 'Build Success',
    description: 'All packages must build without errors',
    status: 'pass',
    metrics: [
      { id: 'QM-001', name: 'Build Time', value: 45, threshold: 120, unit: 's', status: 'pass' },
      { id: 'QM-002', name: 'Bundle Size', value: 187, threshold: 250, unit: 'KB', status: 'pass' },
      { id: 'QM-003', name: 'Type Errors', value: 0, threshold: 0, unit: 'count', status: 'pass' },
    ],
  },
  {
    id: 'QG-002',
    name: 'Test Suite',
    description: 'All tests must pass with adequate coverage',
    status: 'pass',
    metrics: [
      { id: 'QM-004', name: 'Test Pass Rate', value: 98, threshold: 95, unit: '%', status: 'pass' },
      { id: 'QM-005', name: 'Code Coverage', value: 82, threshold: 80, unit: '%', status: 'pass' },
      { id: 'QM-006', name: 'Test Duration', value: 28, threshold: 60, unit: 's', status: 'pass' },
    ],
  },
  {
    id: 'QG-003',
    name: 'Security Scan',
    description: 'No critical or high vulnerabilities',
    status: 'pass',
    metrics: [
      {
        id: 'QM-007',
        name: 'Critical Vulns',
        value: 0,
        threshold: 0,
        unit: 'count',
        status: 'pass',
      },
      { id: 'QM-008', name: 'High Vulns', value: 0, threshold: 0, unit: 'count', status: 'pass' },
      { id: 'QM-009', name: 'Medium Vulns', value: 3, threshold: 5, unit: 'count', status: 'pass' },
    ],
  },
  {
    id: 'QG-004',
    name: 'Performance',
    description: 'Core Web Vitals must meet thresholds',
    status: 'warn',
    metrics: [
      { id: 'QM-010', name: 'LCP', value: 2.8, threshold: 2.5, unit: 's', status: 'warn' },
      { id: 'QM-011', name: 'FID', value: 45, threshold: 100, unit: 'ms', status: 'pass' },
      { id: 'QM-012', name: 'CLS', value: 0.05, threshold: 0.1, unit: 'score', status: 'pass' },
    ],
  },
  {
    id: 'QG-005',
    name: 'Code Quality',
    description: 'Biome linting and formatting checks',
    status: 'pass',
    metrics: [
      { id: 'QM-013', name: 'Lint Errors', value: 0, threshold: 0, unit: 'count', status: 'pass' },
      {
        id: 'QM-014',
        name: 'Format Issues',
        value: 0,
        threshold: 0,
        unit: 'count',
        status: 'pass',
      },
      {
        id: 'QM-015',
        name: 'Complexity Score',
        value: 12,
        threshold: 20,
        unit: 'score',
        status: 'pass',
      },
    ],
  },
  {
    id: 'QG-006',
    name: 'E2E Validation',
    description: 'Critical user flows must work end-to-end',
    status: 'fail',
    metrics: [
      {
        id: 'QM-016',
        name: 'Flow Pass Rate',
        value: 85,
        threshold: 100,
        unit: '%',
        status: 'fail',
      },
      {
        id: 'QM-017',
        name: 'Screenshot Diff',
        value: 2.3,
        threshold: 1.0,
        unit: '%',
        status: 'fail',
      },
      {
        id: 'QM-018',
        name: 'API Response Time',
        value: 180,
        threshold: 200,
        unit: 'ms',
        status: 'pass',
      },
    ],
  },
];

export const auditEvents: AuditEvent[] = [
  {
    id: 'AUD-001',
    timestamp: '2026-07-07T14:30:00Z',
    type: 'Mission Complete',
    severity: 'info',
    result: 'pass',
    description: 'MSN-001 Implement Authentication System completed successfully',
    agent: 'Engineer',
    mission: 'MSN-001',
  },
  {
    id: 'AUD-002',
    timestamp: '2026-07-07T14:25:00Z',
    type: 'Quality Gate',
    severity: 'info',
    result: 'pass',
    description: 'Build Success gate passed - all packages compiled',
    mission: 'MSN-003',
  },
  {
    id: 'AUD-003',
    timestamp: '2026-07-07T14:20:00Z',
    type: 'Governance Check',
    severity: 'medium',
    result: 'warn',
    description: 'LCP exceeded threshold: 2.8s (limit: 2.5s)',
    agent: 'Engineer',
    mission: 'MSN-005',
  },
  {
    id: 'AUD-004',
    timestamp: '2026-07-07T14:15:00Z',
    type: 'Security Scan',
    severity: 'high',
    result: 'fail',
    description: 'E2E validation failed: 2 critical flows broken',
    mission: 'MSN-004',
  },
  {
    id: 'AUD-005',
    timestamp: '2026-07-07T14:10:00Z',
    type: 'Agent Action',
    severity: 'info',
    result: 'pass',
    description: 'Architect initiated database schema review',
    agent: 'Architect',
    mission: 'MSN-003',
  },
  {
    id: 'AUD-006',
    timestamp: '2026-07-07T14:05:00Z',
    type: 'Governance Block',
    severity: 'critical',
    result: 'fail',
    description: 'Attempted to commit hardcoded API key - blocked by GOV-001',
    agent: 'Engineer',
  },
  {
    id: 'AUD-007',
    timestamp: '2026-07-07T14:00:00Z',
    type: 'Mission Start',
    severity: 'info',
    result: 'pass',
    description: 'MSN-008 Mobile App Shell Setup initiated',
    agent: 'Engineer',
    mission: 'MSN-008',
  },
  {
    id: 'AUD-008',
    timestamp: '2026-07-07T13:55:00Z',
    type: 'Quality Gate',
    severity: 'medium',
    result: 'warn',
    description: 'Performance gate warning: LCP approaching threshold',
    mission: 'MSN-005',
  },
  {
    id: 'AUD-009',
    timestamp: '2026-07-07T13:50:00Z',
    type: 'Agent Rebalance',
    severity: 'info',
    result: 'pass',
    description: 'Workload rebalanced: DevOps moved to idle',
    agent: 'DevOps',
  },
  {
    id: 'AUD-010',
    timestamp: '2026-07-07T13:45:00Z',
    type: 'Governance Escalate',
    severity: 'high',
    result: 'warn',
    description: 'Test coverage below threshold: 78% (limit: 80%)',
    agent: 'QA',
    mission: 'MSN-004',
  },
  {
    id: 'AUD-011',
    timestamp: '2026-07-07T13:40:00Z',
    type: 'Security Alert',
    severity: 'critical',
    result: 'fail',
    description: 'Dependency vulnerability detected: lodash prototype pollution',
    agent: 'Security',
  },
  {
    id: 'AUD-012',
    timestamp: '2026-07-07T13:35:00Z',
    type: 'Mission Complete',
    severity: 'info',
    result: 'pass',
    description: 'MSN-006 CI/CD Pipeline Enhancement completed',
    agent: 'DevOps',
    mission: 'MSN-006',
  },
  {
    id: 'AUD-013',
    timestamp: '2026-07-07T13:30:00Z',
    type: 'Quality Gate',
    severity: 'info',
    result: 'pass',
    description: 'Security scan passed: 0 critical, 0 high vulnerabilities',
    mission: 'MSN-004',
  },
  {
    id: 'AUD-014',
    timestamp: '2026-07-07T13:25:00Z',
    type: 'Agent Action',
    severity: 'info',
    result: 'pass',
    description: 'Product updated mission priorities for next sprint',
    agent: 'Product',
  },
  {
    id: 'AUD-015',
    timestamp: '2026-07-07T13:20:00Z',
    type: 'Governance Check',
    severity: 'low',
    result: 'pass',
    description: 'Commit message format validated for 12 commits',
    agent: 'Engineer',
  },
  {
    id: 'AUD-016',
    timestamp: '2026-07-07T13:15:00Z',
    type: 'Mission Failed',
    severity: 'high',
    result: 'fail',
    description: 'MSN-007 API Contract Validation failed - 3 contract mismatches',
    agent: 'QA',
    mission: 'MSN-007',
  },
  {
    id: 'AUD-017',
    timestamp: '2026-07-07T13:10:00Z',
    type: 'Quality Gate',
    severity: 'info',
    result: 'pass',
    description: 'Code quality gate passed: 0 lint errors, 0 format issues',
  },
  {
    id: 'AUD-018',
    timestamp: '2026-07-07T13:05:00Z',
    type: 'Agent Status',
    severity: 'info',
    result: 'pass',
    description: 'Architect status changed: working → idle',
    agent: 'Architect',
  },
  {
    id: 'AUD-019',
    timestamp: '2026-07-07T13:00:00Z',
    type: 'Governance Warn',
    severity: 'medium',
    result: 'warn',
    description: 'Bundle size approaching limit: 235KB (limit: 250KB)',
    agent: 'Engineer',
    mission: 'MSN-005',
  },
  {
    id: 'AUD-020',
    timestamp: '2026-07-07T12:55:00Z',
    type: 'Security Scan',
    severity: 'info',
    result: 'pass',
    description: 'OWASP Top 10 scan completed - all checks passed',
    agent: 'Security',
  },
];

export const dnaPackages: DnaPackage[] = [
  {
    id: 'DNA-001',
    name: 'Enterprise DNA',
    description:
      'Full enterprise governance with strict quality gates, comprehensive audit trails, and multi-level approval workflows. Designed for regulated industries and large-scale deployments.',
    tags: ['enterprise', 'governance', 'compliance', 'audit'],
    personasCount: 12,
    rulesCount: 24,
    qualityGatesCount: 8,
    version: '2.1.0',
    createdAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'DNA-002',
    name: 'Military DNA',
    description:
      'Zero-trust security model with mandatory encryption, air-gapped deployment support, and real-time threat detection. Highest security clearance for defense applications.',
    tags: ['military', 'security', 'zero-trust', 'encryption'],
    personasCount: 8,
    rulesCount: 32,
    qualityGatesCount: 12,
    version: '1.5.0',
    createdAt: '2026-06-15T00:00:00Z',
  },
  {
    id: 'DNA-003',
    name: 'Surgical DNA',
    description:
      'Precision-focused with minimal overhead. Optimized for rapid iteration cycles with automated quality validation and surgical code changes.',
    tags: ['precision', 'minimal', 'rapid', 'automated'],
    personasCount: 6,
    rulesCount: 16,
    qualityGatesCount: 6,
    version: '1.8.2',
    createdAt: '2026-07-01T00:00:00Z',
  },
  {
    id: 'DNA-004',
    name: 'Lean DNA',
    description:
      'Streamlined for startups and small teams. Essential governance only, fast onboarding, and minimal bureaucracy. Focus on shipping speed with safety guardrails.',
    tags: ['lean', 'startup', 'fast', 'essential'],
    personasCount: 4,
    rulesCount: 8,
    qualityGatesCount: 4,
    version: '1.0.0',
    createdAt: '2026-07-05T00:00:00Z',
  },
];
